### ISSUE TITLE
Popcorn TV DNS IP change preventing Native Apple TV apps from working

### ISSUE THREAD

**Issue by Uokereh** [OstlerDev/PopcornTV#104]
I keep running into this issue, i have to always go back and switch my DNS connection back to AUTOMATIC whenever i want to access other Apple TV apps, even after i have closed PopcornTV terminal. Has anyone else come across this issue, its kind of annoying having to change DNS everything i want to run PopcornTV or run other Native Apple TV apps.

any fix or did i do something wrong somewhere?

**Comment by OstlerDev** [comment]
The issue is that PopcornTV is running the new DNS server. If you close PopcornTV then the DNS requests will just 404. You can get around this by just leaving PopcornTV running all the time. If you do not want to leave PopcornTV running then you will need to change the DNS back to Automatic each time you want to use another Application.

Is this the best way? Sadly, it is the only way that our application can work.

**Comment by Uokereh** [comment]
Just wanted to know if it was an issue on my part, I run PopcornTV off my MacBook Pro and I never keep the laptop open at all times. Sounds like I should put PopcornTV on a computer that is always constantly running, so that I don't have to change DNS settings. 

THANKS!

**Comment by OstlerDev** [comment]
No Problem! Happy to clarify.
