### ISSUE TITLE
Trailers is unavailable. Try again later.

### ISSUE THREAD

**Issue by sweetw0r** [OstlerDev/PopcornTV#122]
https://gist.github.com/sweetw0r/ce68bf2653c8bcb48209
After some time of using it stops working. "Trailers is unavailable. Try again later." shows up. All logs attached. I wasn't able to collect Debug log (You need to fix this as well). It was not created after I remove PopcornTV.log and run atv.js Debug. So I attached removed one
The only way to make it work is reset Apple TV and reinstall the PopcornTV from the scratch. But eventually it will be down anyway.
Expected:
1. Fix it 
2. Make it more independent form Apple TV that user would not be forced to reset Apple TV each time.
Please let me now if you have any further questions

**Comment by OstlerDev** [comment]
Firstly, all time is donated to this project and I am not compensated at all for the work I do. It is all done in my own free time because I wanted the app personally, so demanding that I fix it will not help your situation at all.

Secondly, it is pretty much independent of the Apple TV. It seems that you might have deleted the "assets/thumbnails" folder, leading to the error you have.

When you install are you deleting anything that you should not be?

**Comment by sweetw0r** [comment]
1. I understand what you are saying. Personally, I am not expecting from you anything. I just used more bugs report format(Like Expected and Actual result). I am sorry to have confused you. Of course I understand that you are doing it for free.(and bitcoins is not very popular way to get enough donation)

2. Each time after reinstalling or moving or running the app from another Mac with another DNS, I got "Trailers is unavailable." So, I forced to reset both, Apple TV and the app

3. Last time I was executing you wiki instruction with matching 100% and left everything where it should be. Also reseted the Apple TV and it used to work well. But then it has become broken by itself. I didn't move or remove anything for sure. Once problem occurs I removed PopcornTV.log file to collect it in Debug mode > New log file wasn't created.

p.s. I just want to help. Nothing more. Streaming from original PopcornTime Mac app works awesome. Since user is forced to keep mac turned on, the only difference is remote control access.
Anyway, I highly respect and appreciate your time and effort

**Comment by OstlerDev** [comment]
I just wanted to clarify, so its no biggie :) I can only accept Bitcoins because my Paypal account was locked permanently.

If you are running it on a different Mac, it means that the certificate is bad, try just adding the certificate again, without removing the old one. That should clear up the issue for you. Also, you do not need to delete the old log, though restarting the application should regenerate the log file.

Let me know if you need more help! I do appreciate your bug reports, though some of them could be a little more clear.
