### ISSUE TITLE
Thanks, but..

### ISSUE THREAD

**Issue by domidyon** [OstlerDev/PopcornTV#147]
Hi OstlerDev,

Thanks for making this possible! Sadly, this doesn't work for everyone. I did everything according to the installation guide, tried this on windows AND mac, tried importing the profile via the configurator, but nothing works. I think i'm just one of the unlucky people for which this will never work. 
I am giving up now, but thanks for trying to help me.

If you have any suggestions aside from rebooting my Apple TV or checking the DNS adress, i'd love to hear them.

**Comment by OstlerDev** [comment]
I wish that for your situation there was just a quick fix, unfortunately I am not able to find why the error is happening for you. The main thing I think it might be is that they might be on different Wifi Networks. Do you have wifi extenders in your house?

Your situation is sadly so unique that we cannot diagnose the problem :/

It could be that your desktop is connected via ethernet to a different network and wifi to the same network, but is binding to the ethernet IP instead of the Wifi.

All in all, sad that it couldn't work, but best of luck!
