### ISSUE TITLE
Does this mean I can also run other applications on the Apple TV also (if I modified the source code)?

### ISSUE THREAD

**Issue by losh11** [OstlerDev/PopcornTV#148]
Might consider running a secure dos server that other people can use...

**Comment by OstlerDev** [comment]
Yep! As long as you generate and send valid XML to the Apple TV you can create it for any Application.

Feel free to borrow any of my code, just be sure to attribute it correctly.

**Comment by losh11** [comment]
@OstlerDev How long do you reckon before Apple patches this?
Because I had a friend who use a similar sort of method to load stuff on a iPhone - what it would do was the dns faked the apple server and since the link was a http link with no ssl, he was able to intercept and pose as that server, whilst loading content onto it. It got patching within two months.

Also have you tried installing on a Linux system, because that's what I'm going to try to do next.

**Comment by OstlerDev** [comment]
I have run this on Linux servers perfectly fine, also this method has been working for multiple years now with no patching at all. The way it works makes it /near/ unpatchable unless they completely removed the ability for the SSL certs.

I imagine that it will remain unpatched until the next massive update (unknown). I have disabled automatic updates when users are running this so that if it does get patched, users that are running lesser software will still be able to run it.

**Comment by losh11** [comment]
Have you tested this running over a public ip?

Because I can't get it to work...
I kept config.json using the private ip, and then tried connecting with the
public ip, didn't work.
I then changed the config.json file to use my public ip, but when trying to
run the program, the software comes up with an error saying fatal error and
something about having the wrong ip address.

**Comment by OstlerDev** [comment]
I have run it on a public IP before, just make sure that you have the correct IP entered in and that you have those ports open publicly on your server.
