### ISSUE TITLE
Subtitles not sycroon + data lag

### ISSUE THREAD

**Issue by Ibrahim24** [OstlerDev/PopcornTV#155]
It looks like when I'm watching movies and use dutch subtitles these are not syncroon. 

And I do experience data lag, using both WIFI connection keeps the lag away for some time.

**Comment by OstlerDev** [comment]
Sometimes subtitles will not be synchronized with the movie, this is a problem because the video file the subtitle was made for is different than the file that it is playing. Basically the subtitles were made for File 2, and we are playing File 1, so some lag is expected.

As for the data lag there is nothing that I can do for you there,
