### ISSUE TITLE
Tutorial Video

### ISSUE THREAD

**Issue by Mehmeed** [OstlerDev/PopcornTV#35]
Here's the link:
https://www.youtube.com/watch?v=x_A58Ttvjd0

It was made in hurry so please excuse any mistakes. I'll make another one, once your project is finished.

**Comment by OstlerDev** [comment]
Thanks for posting it! I am getting closer to releasing v0.1.5, which this has most of the same features. I do not think the project will ever really be done, as I have many ideas on how to make it better and such. I have added your video to the windows install page so that people can watch it a little easier!

Thanks for the work you have done!
