### ISSUE TITLE
Support for manually adding magnet/torrent links

### ISSUE THREAD

**Issue by SteveAbb** [OstlerDev/PopcornTV#37]
Hi,

Would it be possible to add support for manually pasting in a magnet/torrent link somewhere into the Trailers app and having it begin streaming? Or maybe allow for an HTTP JSON-RPC request to the PopcornTV server with a magnet/torrent link -- similar to how Pulsar works? I know things are more limited since you have to work through the Trailer app's UI by intercepting it's requests, but just curious if this has already been thought of.

Thanks,
Steve

**Comment by OstlerDev** [comment]
I have never seen Pulsar but I could look into it! It is something that I have looked into, because it is also something that I would want to work. There are a few issues with making it work right off the bat like that however.

1. The XML is static, unless I can somehow call a method to check for Magnet links (similar to a callback)
2. I cannot live edit the XML (which is what is preventing me from loading more then 50 results). I can only load a new page, which for this would not be bad, I just need to know when to load a page.

I am thinking of one of the following to be a solution:

1. Allow for people to search for torrents using Strike (add another search option)
2. Figure out how to make a callback to the Javascript that I can load in the XML.

Out of those two options, I will most likely go with the first one. That way people can search for movies or TV shows that have not been added to YTS or the eztvapi (which will shortly be swapped out for Getstrike).

**Comment by OstlerDev** [comment]
If this is added it will be in the desktop Application found at OstlerDev/PopcornTV-App/issues/12
