### ISSUE TITLE
Problem resuming stream.

### ISSUE THREAD

**Issue by JHFreeman** [OstlerDev/PopcornTV#50]
I stopped a stream then went to resume it, however, it doesn't start on the apple tv, the Debug log shows the torrent as if it were cached and "downloads" it very quickly to 100% but nothing starts on the tv, is it cached somewhere I can delete it? I've tried to remove the .mp4 file in the PTV directory but that didn't help or change any behavior. The mp4 file just reappears as if it were never deleted. I'm running the latest commit.

https://gist.github.com/seeitbelieveit/283a86267b459b7b9ea5

edit: I've also tried deleting the PTV directory and redownloading from the repo, and problem still exists, I recreated the profile on apple tv with no luck.

**Comment by OstlerDev** [comment]
The issue happens because torrents are downloaded to /tmp/torrent-stream

For some reason starting the same torrent again throws an error, but if you start another stream then go back to the old one it works fine. This is a bug that I need to resolve.

**Comment by seeitbelieveit** [comment]
I cleared /tmp/torrent-stream, redownloaded the repo, and deleted/recreated trailers profile. Now, when I try to start a stream, the download works correctly based on the log, but when the log shows its ready to stream and sets up the port, the 'Accessing Trailers...' message goes away and all I'm left with is the spinner.

**Comment by OstlerDev** [comment]
In the settings page try turning "Keep Movies" to "Off" and report back.

**Comment by seeitbelieveit** [comment]
Didn't make a difference.

I tried turning the atv off/on and when I went to try and play an episode I got a crash:

https://gist.github.com/seeitbelieveit/7f1e60f1305bda9dc84d

**Comment by OstlerDev** [comment]
Try starting a movie then going back and attempting again. There could be an issue with your network possibily. Have you been able to stream at all?

**Comment by seeitbelieveit** [comment]
yes, I am able to stream, I just tried again at the stream got hung up at about 30 seconds in, which has happened a few times. Went back to episode view then did play again and it started up with no pauses so far, right now trying to resume at the position I was in when I stopped it earlier, will report back.

As for my network,
I have the PopcornTV laptop set to 192.168.0.5 based on mac address at the router, so that never changes, it doesn't seem to have many options though as its a combo router/cable modem from the provider, I'm open to trying a different router to see if anything is different, as I have a couple laying around.

**Comment by OstlerDev** [comment]
The reason I think you were having an issue with your network was because the spinner was going. That means that it bound to the port but was not streaming the file for some reason.

We will keep an eye on this. I will try to fix that bug with the streamer and see if that fixes it.

**Comment by OstlerDev** [comment]
I tested last night and I am stopping and resuming streams perfectly fine once they are fully downloaded. I do need to look into why the stream stops however.

**Comment by OstlerDev** [comment]
Bringing this back. There is an issue with the torrent not resuming correctly when only part of the download is done. I am thinking this might have to do with telling the torrent-stream server to resume the stream instead of attempting to start a new one.

Take a look here: https://git.popcorntime.io/popcorntime/streamer/blob/master/streamers/torrent.js#L19
And here(?): https://github.com/mafintosh/torrent-stream/blob/master/index.js#L75

**Comment by seeitbelieveit** [comment]
Sorry I'm not familiar enough with their code to know what's completely going on.
I've been reading into node.js and was wondering if the single treading is causing some of the issues since the servers may be blocking each other from functioning at certain key points, is this a possibility?

**Comment by OstlerDev** [comment]
Your fine for not understanding the code 100%, it is pretty complex.

Most of the code is asynchronous so we do not need to really worry about streaming overlap. I believe the issue is that the torrent is only told to verify, but then does not resume downloading after it verifies the already downloaded content. I believe this is an issue within the "popcorn-streamer" but I am seeing what exactly I can do because of it.
