### ISSUE TITLE
trailers is unavailable

### ISSUE THREAD

**Issue by garcias91** [OstlerDev/PopcornTV#6]
I followed the directions for the install to the letter, and now when I try to use the Trailers app all I get is a message saying Trailers is unavailable. Try again later. Is this a common error, or did I do something wrong?

**Comment by OstlerDev** [comment]
This usually happens because the profile was added incorrectly. Try going back and re-adding the profile. It should take you to a page that says "Add Profile" up top and have a new section that says "trailers.apple.com". If you see that then you have done it correctly.

Does your log say anything after it starts up? It should say stuff about redirecting the DNS for the certificate as well as when you attempt to access the trailers app.

Please post the last bit of the logs to pastebin please :).

**Comment by garcias91** [comment]
it still says trailers.apple.com, what's the whole thing with logs? is that on the mac aspect? and also would it matter if its a brand new apple tv?

**Comment by OstlerDev** [comment]
@garcias91 It shouldnt matter if it is a brand new Apple TV, I have tested that just fine. And the logs would be the terminal window that you have open, yes.

Make sure that you are running PopcornTV when accessing the Trailers Application then let me know!

**Comment by garcias91** [comment]
It works! Thank you! I have a side question, I know on popcorntime they offer vpn. Is there a way to do this with popcorn tv or is there no need for it?

**Comment by OstlerDev** [comment]
No problem! Currenly the only way to enable VPN support would be to turn on a VPN on your computer. It would also shield the traffic on PopcornTV. In the future I plan to build in some VPN support possibily, but just running a VPN on the main computer will work fine :p
