### ISSUE TITLE
Minor Improvements

### ISSUE THREAD

**Issue by JakeRound** [OstlerDev/PopcornTV#65]
Hey, Just noted two small improvements that i was wondering if were possible?

Occasional stuttering on opening Movies / TV pages, especially with the first tab being opened being 'Popular' sometime's i'm given the message 'Accessing Trailer' (it refuses to load unless following ->) in order for me to fix without rebooting the server requires me to access another tab then reverting back to 'popular' xml page in order for it to work.

Are you able to rewrite the XML output in-between the loading screens currently is says 'Accessing Trailer' to output something similar to 'Loading Movie' or something or is this a limitation natively written for the Trailers app that can't be modified?

**Comment by OstlerDev** [comment]
1. This happens because it is trying to serve an old XML file (usually the parade for the movie posters on the home screen). I am looking into a workaround for this :)
2. Sadly as far as I am aware, no, I cannot without a major workaround of how the application is done. It is a limitation of the Apple TV. It will say "Accessing " + the Application name.

As for the loading issue, I will be working on this tomorrow.

**Comment by JakeRound** [comment]
Thanks for the response! I assumed so that you're unable to change to Accessing message, thanks for having a look into the first of the loading page :+1:

**Comment by OstlerDev** [comment]
I could possibly add a download status to the stream loading part, however that would require a lot more work. Will look into it in the future.
