### ISSUE TITLE
Subtitles changing accents for no purpose. 

### ISSUE THREAD

**Issue by Mehmeed** [OstlerDev/PopcornTV#80]
So.. subtitles are working fine and everythings great.. but i noticed that sometime subtitle changes their accent for no reason.. i mean they get bold, thin and italic.. well i know when someone is narrating in a movie, their subtitles go either italic or bold.. but it seems like its doing that for no reason.. please note its not a complain.. i'm just saying this to help you improve your project. and it would be awesome if subtiltes were in helvetica nueue light or thin... :)

**Comment by OstlerDev** [comment]
This happens because the subtitle author specifically stated that it should be bold or italic. When it's encoded like below inside the file it will show up as such.

```
<b> I will be Bold </b>
<i> I will be thin </i>
```

As for the font I am using the default font for Apples text renderer. I may look into switching it but I feel that the current one does just fine.
